// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ2hXeEFDs6l4IiGSo5TYHatiWkSiOfgY',
    appId: '1:345810929805:web:dfbc3de193b0021db43ac4',
    messagingSenderId: '345810929805',
    projectId: 'elecnorcalculoflechas',
    authDomain: 'elecnorcalculoflechas.firebaseapp.com',
    storageBucket: 'elecnorcalculoflechas.appspot.com',
    measurementId: 'G-X5G3T2H47B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoWQ7KsHCM6bBF9G0KMMS9Tx6wilbt5Ac',
    appId: '1:345810929805:android:426180f3e146a878b43ac4',
    messagingSenderId: '345810929805',
    projectId: 'elecnorcalculoflechas',
    storageBucket: 'elecnorcalculoflechas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsc3Eb9LBtWm_fRJ6VhmBGjQMpcKVVHs8',
    appId: '1:345810929805:ios:09b7c875f924cefdb43ac4',
    messagingSenderId: '345810929805',
    projectId: 'elecnorcalculoflechas',
    storageBucket: 'elecnorcalculoflechas.appspot.com',
    iosBundleId: 'com.example.elecnorappflechas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsc3Eb9LBtWm_fRJ6VhmBGjQMpcKVVHs8',
    appId: '1:345810929805:ios:d8a0f558e4205756b43ac4',
    messagingSenderId: '345810929805',
    projectId: 'elecnorcalculoflechas',
    storageBucket: 'elecnorcalculoflechas.appspot.com',
    iosBundleId: 'com.example.elecnorappflechas.RunnerTests',
  );
}
